# This file is generated by hatch-vcs at build time. Do not edit manually.
# During development (no build), provide a sensible fallback.
try:
    from importlib.metadata import version

    __version__ = version("af-mcp-broker")
    version_tuple = tuple(int(x) for x in __version__.split(".")[:3])
except Exception:
    __version__ = "0.0.0.dev0"
    version_tuple = (0, 0, 0, "dev", "0")
